# Generated by Django 5.0.14 on 2026-03-27 14:03 (manually edited to fix unique referral_code)

import uuid
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.referral_code = uuid.uuid4().hex[:8].upper()
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_active_date_customuser_streak_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('FIRST_TEST', '🎯 First Test'), ('FIRST_PASS', '🏆 First Pass'), ('FIRST_EARN', '💰 First Earn'), ('REFERRAL', '🤝 Referral Star'), ('STREAK_7', '🔥 7-Day Streak'), ('STREAK_30', '⚡ 30-Day Streak')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏅', max_length=10)),
            ],
        ),
        # Step 1: Add referral_code as nullable (no unique yet)
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        # Step 2: Populate unique codes for all existing users
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        # Step 3: Make it unique and non-nullable
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=users.models._gen_referral_code, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
