# Generated by Django 5.0.14 on 2026-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_badge_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trial_tests_left',
            field=models.IntegerField(default=3),
        ),
    ]
