# Generated by Django 5.0.14 on 2026-04-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ad_claim_at',
            field=models.DateTimeField(blank=True, help_text='Server-side last ad reward claim (anti-abuse).', null=True),
        ),
        migrations.CreateModel(
            name='CompanyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('READ', 'Read')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
