# Generated by Django 5.0.14 on 2026-04-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_public_profile_ad_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trial_tests_used',
            field=models.IntegerField(default=0, help_text='Lifetime trials consumed (prevents cookie/session reset abuse).'),
        ),
    ]
