# Generated by Django 5.0.14 on 2026-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_trial_tests_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TUTOR', 'Tutor')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
