# Generated by Django 5.0.14 on 2026-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TUTOR', 'Tutor'), ('CITY_ADMIN', 'City admin'), ('GLOBAL_ADMIN', 'Global admin')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
