# Generated by Django 5.0.14 on 2026-04-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vip_testing_user',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, user always has exam Pro access (feedback / QA). Manage from /sd/.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signup_pro_trial_applied_at',
            field=models.DateTimeField(blank=True, help_text='Set when the one-time signup Pro trial was applied (payments module).', null=True),
        ),
    ]
