# Generated by Django 5.0.14 on 2026-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vip_testing_signup_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(db_index=True, default=True, help_text='Role/profile onboarding completion gate for login redirects.'),
        ),
    ]
