# Generated by Django 5.0.14 on 2026-07-31 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_is_lms_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_label', models.CharField(blank=True, help_text='e.g. Mother, Father, Guardian', max_length=40)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Student must approve before the parent gets any read-only access.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(help_text='The Parent account requesting visibility.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The Student account being viewed.', on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='parentstudentlink',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_link'),
        ),
    ]
