# Generated by Django 5.0.14 on 2026-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_parentstudentlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City the user lives/teaches in.', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Mobile number (Indian 10-digit, optional +91).', max_length=15),
        ),
    ]
