# Generated by Django 5.0.14 on 2026-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_city_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Locality/area within the city (optional).', max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Student's class/grade (1–12).", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.CharField(blank=True, default='', help_text="Comma-separated subjects of interest, e.g. 'Maths, Science'.", max_length=200),
        ),
    ]
