# Generated by Django 5.0.14 on 2026-08-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_userattempt_passed_and_more'),
        ('users', '0020_customuser_area_customuser_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, help_text="Student's class/program — Class 1-12, MBA, MTech, or any other level a superadmin has added at /admin/cms/skill-paths/. Drives LMS content gating and dashboard personalization; replaces the old class-1-to-12-only limit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='assessment.skillpath'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Student's class/grade (1–12). Legacy numeric mirror of `level` — kept for code that still filters by grade number; auto-derived from `level` when it names a school class.", null=True),
        ),
    ]
