# Generated by Django 5.0.14 on 2026-03-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('level_order', models.IntegerField(default=1, help_text='e.g. 1=Beginner, 2=Pro, 3=Earner')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level_order'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='assessment.skillpath'),
        ),
    ]
