# Generated by Django 5.0.1 on 2026-03-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_skillpath_skill_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in the learning sequence'),
        ),
    ]
