# Generated by Django 5.0.14 on 2026-03-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_question_skill_questionset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJackpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='Time when the jackpot quiz goes live (e.g. 9:00 PM)')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpots', to='assessment.skill')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='JackpotWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.IntegerField()),
                ('time_taken_seconds', models.IntegerField()),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('jackpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='assessment.dailyjackpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('jackpot', 'user')},
            },
        ),
    ]
