# Generated by Django 5.0.14 on 2026-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_dailyjackpot_jackpotwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer shown upon failing'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersetattempt',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
