# Generated by Django 5.0.14 on 2026-04-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_skilltestentitlement'),
        ('learning', '0004_revision_bites'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_video_import',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='source_video',
            field=models.ForeignKey(blank=True, help_text='If set, this question is linked to a specific learning video import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_questions', to='learning.conceptvideo'),
        ),
    ]
