# Generated by Django 5.0.14 on 2026-07-20 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_userattempt_attempted_video'),
        ('learning', '0004_revision_bites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='passed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'attempt_date'], name='assessment__user_id_c6b9e4_idx'),
        ),
    ]
