# Generated by Django 5.0.14 on 2026-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningtask',
            name='auto_approve_domain',
            field=models.CharField(blank=True, help_text='If proof URL contains this domain, auto-approve the submission (e.g. youtube.com)', max_length=100),
        ),
    ]
