# Generated by Django 5.0.14 on 2026-04-30 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_default_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_type', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=12)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('class_grade', models.CharField(blank=True, help_text='e.g. 8, 10, 12', max_length=20)),
                ('board', models.CharField(blank=True, help_text='CBSE / ICSE / GSEB / IB / Other', max_length=40)),
                ('subjects', models.CharField(help_text='Comma-separated subjects', max_length=250)),
                ('teaching_mode', models.CharField(blank=True, help_text='Online / Offline / Hybrid', max_length=20)),
                ('budget_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date_text', models.CharField(blank=True, help_text='When to start', max_length=60)),
                ('schedule_notes', models.CharField(blank=True, max_length=250)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_lead_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
