# Generated by Django 5.0.14 on 2026-05-07 13:38

from django.db import migrations, models


def seed_default_legal_pages(apps, schema_editor):
    LegalPage = apps.get_model("core", "LegalPage")
    defaults = {
        "terms-and-conditions": {
            "title": "Terms and Conditions",
            "content": (
                "Welcome to RankJee. By using our platform (tutors, courses, exams, and earning features), "
                "you agree to these terms.\n\n"
                "Accounts must use accurate details. Misuse, abuse, fraud, scraping, or policy violations may "
                "lead to suspension. Paid features are activated only after successful payment verification. "
                "Digital services are provided on an as-available basis, and outcomes may vary by user effort."
            ),
        },
        "privacy-policy": {
            "title": "Privacy Policy",
            "content": (
                "We collect account, usage, and transaction data needed to deliver and improve RankJee. "
                "We use this information for platform operations, support, security, and compliance.\n\n"
                "We do not sell personal data. Data may be shared with trusted processors (hosting, payments, "
                "email, analytics) and legal authorities when required by law."
            ),
        },
        "cancellation-and-refund": {
            "title": "Cancellation and Refund",
            "content": (
                "For digital services, cancellation after successful activation may be limited. "
                "Duplicate charges and verified non-delivery issues are eligible for review.\n\n"
                "To request support, share order/payment details and registered account email."
            ),
        },
        "shipping-and-exchange": {
            "title": "Shipping and Exchange",
            "content": (
                "RankJee primarily delivers digital services; physical shipping generally does not apply. "
                "Access is typically provisioned after payment verification.\n\n"
                "Digital products are generally non-exchangeable, except platform-side errors after review."
            ),
        },
        "contact-us": {
            "title": "Contact Us",
            "content": (
                "For account, payment, tutor, course, or exam support, contact RankJee with your registered email "
                "and relevant order/reference IDs for faster resolution."
            ),
        },
    }
    for slug, item in defaults.items():
        LegalPage.objects.update_or_create(
            slug=slug,
            defaults={
                "title": item["title"],
                "content": item["content"],
                "seo_title": f'{item["title"]} | RankJee',
                "seo_description": item["content"][:155],
                "is_published": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_referral_commission_18_and_buyer_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terms-and-conditions', 'Terms and Conditions'), ('privacy-policy', 'Privacy Policy'), ('cancellation-and-refund', 'Cancellation and Refund'), ('shipping-and-exchange', 'Shipping and Exchange'), ('contact-us', 'Contact Us')], max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(help_text='Main page content. Use short paragraphs and bullet lines.')),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.RunPython(seed_default_legal_pages, migrations.RunPython.noop),
    ]
