# Generated by Django 5.0.14 on 2026-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_legalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"module":"M1","title":"Foundations","topics":["Topic A","Topic B"]}]'),
        ),
        migrations.AddField(
            model_name='course',
            name='job_roles',
            field=models.TextField(blank=True, help_text='Comma-separated job roles after this course. e.g. SEO Analyst, Content Strategist'),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_after_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Max expected salary in LPA after completing this course', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_after_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Min expected salary in LPA after completing this course', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='testimonials',
            field=models.JSONField(blank=True, default=list, help_text='JSON: [{"name":"Priya","role":"Marketer","city":"Mumbai","text":"...","rating":5}]'),
        ),
    ]
