# Generated by Django 5.0.14 on 2026-08-02 10:49

from django.db import migrations, models


def backfill_null_json_fields_sqlite(apps, schema_editor):
    """SQLite only: rows seeded by 0004 predate the JSON columns; 0012 patched those
    columns in as nullable, so seeded rows can hold NULL there. The AddField ops below
    trigger a SQLite table rebuild that re-declares them NOT NULL — backfill '[]' first
    or the rebuild's INSERT..SELECT fails. No-op on Postgres (0010 added real defaults)."""
    if schema_editor.connection.vendor != 'sqlite':
        return
    table = apps.get_model('core', 'Course')._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'PRAGMA table_info({table})')
        existing = {row[1] for row in cursor.fetchall()}
        for name in ('course_includes', 'gain_outcomes', 'gain_perks', 'hero_usps'):
            if name in existing:
                cursor.execute(f'UPDATE "{table}" SET "{name}" = \'[]\' WHERE "{name}" IS NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_course_json_fields_sqlite'),
    ]

    operations = [
        migrations.RunPython(backfill_null_json_fields_sqlite, migrations.RunPython.noop),
        migrations.AddField(
            model_name='course',
            name='allow_monthly',
            field=models.BooleanField(default=False, help_text='Offer a 30-day monthly purchase option alongside the one-time price.'),
        ),
        migrations.AddField(
            model_name='course',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Target class/grade 1–12 (for academic courses; blank for skill courses).', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 30-day access; required if monthly is allowed.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
