# Generated by Django 5.0.14 on 2026-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_allow_monthly_course_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorderline',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
