# Generated by Django 5.0.14 on 2026-08-02 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_courseorderline_is_monthly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('RECORDED', 'Recorded'), ('HYBRID', 'Hybrid (Professional)')], db_index=True, default='RECORDED', help_text='Recorded = instant free preview + buy. Hybrid = request a live demo class from the assigned faculty.', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseDemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('PREVIEW', 'Free preview'), ('LIVE_DEMO', 'Live demo class')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('message', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_faculty', models.ForeignKey(blank=True, help_text="Resolved from the catalog course's default LMS batch owner.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_demo_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_requests', to='core.course')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_demo_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_faculty', 'status'], name='core_course_assigne_6aa90d_idx')],
            },
        ),
    ]
