"""
Django settings for rankjee project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7o*(o1ovr)l&1pn)g2ie8+^q9dzx8h++%rj)x^%!ljr=7u8r_=')

def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
# Safe defaulting:
# - If DEBUG is explicitly set, honor it.
# - If missing, prefer DEBUG=False when DATABASE_URL is configured (typical prod signal).
# - Keep DEBUG=True for pure local/dev sqlite setups without DATABASE_URL.
DEBUG = _env_bool('DEBUG', default=not bool(os.environ.get('DATABASE_URL')))

_raw_hosts = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()] if _raw_hosts else []
if not ALLOWED_HOSTS:
    _site_for_hosts = os.environ.get('SITE_BASE_URL', '').strip()
    if _site_for_hosts:
        parsed = urlparse(_site_for_hosts)
        if parsed.hostname:
            ALLOWED_HOSTS = [parsed.hostname]

# TLS terminated at Nginx: trust X-Forwarded-* for redirects, cookies, CSRF (production only).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
    CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
    # Optional: share auth+csrf cookies across apex/www, e.g. ".rankjee.com".
    _cookie_domain = os.environ.get('COOKIE_DOMAIN', '').strip()
    if _cookie_domain:
        SESSION_COOKIE_DOMAIN = _cookie_domain
        CSRF_COOKIE_DOMAIN = _cookie_domain

    # HSTS: sent on HTTPS responses when the request is treated as secure (incl. behind proxy).
    # Set SECURE_HSTS_SECONDS=0 in .env to disable. Read Django docs before enabling preload/subdomains.
    _hsts = os.environ.get('SECURE_HSTS_SECONDS', '31536000').strip()
    SECURE_HSTS_SECONDS = int(_hsts) if _hsts.isdigit() else 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', '0').lower() in ('1', 'true', 'yes')
    )
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', '0').lower() in ('1', 'true', 'yes')

    # Force end users onto HTTPS; can be disabled explicitly if needed.
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=True)

    # W008: HTTPS is enforced at Nginx, not in Django (see above).
    # W005 / W021: optional HSTS subdomain + preload; off by default until you opt in via env.
    _silenced = []
    if not SECURE_SSL_REDIRECT:
        _silenced.append('security.W008')
    if not SECURE_HSTS_INCLUDE_SUBDOMAINS:
        _silenced.append('security.W005')
    if not SECURE_HSTS_PRELOAD:
        _silenced.append('security.W021')
    SILENCED_SYSTEM_CHECKS = _silenced


def _csrf_trusted_origins():
    """HTTPS + reverse-proxy setups need explicit origins; merge env with ALLOWED_HOSTS / SITE_BASE_URL."""
    raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    origins = [o.strip() for o in raw.split(',') if o.strip()]
    if DEBUG:
        return origins

    def _add(url):
        if url and url not in origins:
            origins.append(url)

    site = os.environ.get('SITE_BASE_URL', '').strip().rstrip('/')
    _add(site)

    for host in ALLOWED_HOSTS:
        h = host.split(':')[0].strip().lower()
        if not h or h in ('127.0.0.1', 'localhost'):
            continue
        parts = h.split('.')
        is_ipv4 = len(parts) == 4 and all(p.isdigit() for p in parts)
        if is_ipv4:
            _add(f'http://{host}')
            _add(f'https://{host}')
            continue
        _add(f'https://{h}')

    return origins


CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Local Apps
    'core',
    'users',
    'dashboard',
    'assessment',
    'learning',
    'payments',
    'hometutor',
    'hometutor_payments',
    'django_celery_beat',
    'axes',
]

# ... existing settings ...

# Razorpay — use dashboard test keys in .env, or leave empty in DEBUG for dummy checkout
# Set RAZORPAY_USE_DUMMY=1 to force simulated payments even if keys exist (local only).
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
# Razorpay webhooks (payment.captured) for home tutor marketplace — verify X-Razorpay-Signature
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '').strip()

# Home tutor marketplace (separate from subscription `payments`)
HOMETUTOR_DEFAULT_MONTHLY_FEE_INR = os.environ.get('HOMETUTOR_DEFAULT_MONTHLY_FEE_INR', '5000')
HOMETUTOR_PLATFORM_FEE_PERCENT = os.environ.get('HOMETUTOR_PLATFORM_FEE_PERCENT', '15')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'rankjee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'rankjee.jinja2.environment',
            'autoescape': True,
            'extensions': [
                'jinja2.ext.i18n',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'users.context_processors.ui_labels',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'django_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rankjee.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    import dj_database_url

    _db_url = os.environ.get('DATABASE_URL', '').strip()
    if not _db_url:
        raise ImproperlyConfigured(
            'DATABASE_URL is required when DEBUG=False. '
            'Use PostgreSQL, e.g. postgres://USER:PASSWORD@HOST:5432/DBNAME'
        )
    _conn_max_age = int(os.environ.get('DB_CONN_MAX_AGE', '600'))
    DATABASES = {
        'default': dj_database_url.config(
            default=_db_url,
            conn_max_age=_conn_max_age,
        )
    }
    _engine = DATABASES['default'].get('ENGINE', '')
    if 'postgresql' not in _engine:
        raise ImproperlyConfigured(
            f'Production DATABASE_URL must use PostgreSQL (django.db.backends.postgresql). '
            f'Got ENGINE={_engine!r}.'
        )

# Production-only Static File Configuration (WhiteNoise)
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
_static_dir = BASE_DIR / 'static'
STATICFILES_DIRS = [_static_dir] if _static_dir.is_dir() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'
SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://127.0.0.1:8000').rstrip('/')
SITE_ID = int(os.environ.get('SITE_ID', '1'))

# django-allauth account settings
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'users.adapters.RoleAwareSocialAccountAdapter'

# Google OAuth credentials from environment (recommended for deploys).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '').strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '').strip()
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
            'key': '',
        },
    },
}

# Testing helper: unlock temporary Pro on signup via referral code.
# Keep disabled in strict production by setting REFERRAL_PREMIUM_ENABLED=0.
REFERRAL_PREMIUM_ENABLED = os.environ.get('REFERRAL_PREMIUM_ENABLED', '1').lower() in ('1', 'true', 'yes')
REFERRAL_PREMIUM_DAYS = int(os.environ.get('REFERRAL_PREMIUM_DAYS', '30'))

# One-time exam Pro trial after new account (payments module); stacks before referral premium on email signup.
SIGNUP_TRIAL_ENABLED = os.environ.get('SIGNUP_TRIAL_ENABLED', '1').lower() in ('1', 'true', 'yes')
SIGNUP_TRIAL_DAYS = int(os.environ.get('SIGNUP_TRIAL_DAYS', '7'))

# Celery Configuration
_redis_default = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', _redis_default)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_IGNORE_RESULT = os.environ.get('CELERY_TASK_IGNORE_RESULT', 'True') == 'True'

# Cache: Redis in production when REDIS_URL is set (unless USE_REDIS_CACHE=0); LocMem for local dev.
_redis_cache_url = os.environ.get('REDIS_CACHE_URL') or _redis_default.replace('/0', '/2')
_use_redis_cache_explicit = os.environ.get('USE_REDIS_CACHE', '').lower()
_disable_redis_cache = _use_redis_cache_explicit in ('0', 'false', 'no')
_enable_redis_cache = (
    not _disable_redis_cache
    and os.environ.get('REDIS_URL')
    and (
        _use_redis_cache_explicit in ('1', 'true', 'yes')
        or (not DEBUG)
    )
)
if _enable_redis_cache:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_cache_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rankjee-locmem',
        }
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '%(asctime)s %(levelname)s %(name)s %(message)s'},
        'simple': {'format': '%(levelname)s %(message)s'},
    },
    'handlers': {
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'app.log',
            'maxBytes': 5_000_000,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['file', 'console'], 'level': 'WARNING', 'propagate': False},
        'rankjee': {'handlers': ['file', 'console'], 'level': 'INFO', 'propagate': False},
    },
}
