from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('vip/smart/', views.vip_smart_dashboard, name='vip_smart'),
    path('vip/add-user/', views.vip_create_user, name='vip_create_user'),
    path('blog/new/', views.blog_post_create, name='blog_post_create'),
    path('blog/<slug:slug>/edit/', views.blog_post_edit, name='blog_post_edit'),
    path('backups/', views.backup_center, name='backup_center'),
    path('backups/create/', views.backup_create_now, name='backup_create_now'),
    path('backups/<int:backup_id>/download/', views.backup_download, name='backup_download'),
    path('backups/<int:backup_id>/delete/', views.backup_delete, name='backup_delete'),
    # Backward-compatible alias for already-open forms/bookmarks.
    path('vip/blog/new/', views.blog_post_create, name='vip_blog_post_create'),
    path('study/', views.dashboard_study, name='study'),
    path('study/topic/general/', views.dashboard_study_topic_general, name='study_topic_general'),
    path('study/topic/<int:topic_pk>/', views.dashboard_study_topic, name='study_topic'),
    path('study/material/<int:pk>/', views.dashboard_study_material, name='study_material'),
    path('study/assignment/<int:pk>/', views.dashboard_study_assignment, name='study_assignment'),
    path('tutor-requests/<int:request_id>/status/', views.update_tutor_request_status, name='update_tutor_request_status'),
    path('seo/smart-view/', views.seo_smart_view, name='seo_smart_view'),
    path('students/daily-class-log/', views.daily_class_log, name='daily_class_log'),
    path('students/daily-class-log/admin/', views.admin_student_daily_logs, name='admin_student_daily_logs'),
    path('students/scores/', views.students_score_table, name='students_score_table'),
    path('attempts/<int:attempt_id>/review/', views.attempt_review, name='attempt_review'),
    path('students/attempts/<int:attempt_id>/review/', views.student_attempt_review, name='student_attempt_review'),
    path('users/referrals/', views.users_referral_table, name='users_referral_table'),
    path('users/server-buy-access/', views.server_buy_access_manage, name='server_buy_access_manage'),
    path('users/<int:user_id>/server-buy-toggle/', views.toggle_user_server_buy, name='toggle_user_server_buy'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/<int:note_id>/read/', views.mark_notification_read, name='mark_read'),
    path('recharge/', views.recharge_wallet, name='recharge'),
    path('imports/questions/', views.import_questions_csv, name='import_questions'),
    path('ai/generate-mcqs/', views.ai_generate_mcqs, name='ai_generate_mcqs'),
    path('cms/', views.cms_home, name='cms_home'),
    path('cms/paths/', views.cms_skillpaths, name='cms_skillpaths'),
    path('cms/paths/new/', views.cms_skillpath_edit, name='cms_skillpath_new'),
    path('cms/paths/<int:pk>/', views.cms_skillpath_edit, name='cms_skillpath_edit'),
    path('cms/skills/', views.cms_skills, name='cms_skills'),
    path('cms/skills/new/', views.cms_skill_edit, name='cms_skill_new'),
    path('cms/skills/<int:pk>/', views.cms_skill_edit, name='cms_skill_edit'),
    path('cms/questions/', views.cms_questions, name='cms_questions'),
    path('cms/questions/new/', views.cms_question_edit, name='cms_question_new'),
    path('cms/questions/<int:pk>/', views.cms_question_edit, name='cms_question_edit'),
    path('cms/videos/', views.cms_videos, name='cms_videos'),
    path('cms/videos/new/', views.cms_video_edit, name='cms_video_new'),
    path('cms/videos/<int:pk>/', views.cms_video_edit, name='cms_video_edit'),
    path('cms/tasks/', views.cms_tasks, name='cms_tasks'),
    path('cms/tasks/new/', views.cms_task_edit, name='cms_task_new'),
    path('cms/tasks/<int:pk>/', views.cms_task_edit, name='cms_task_edit'),
]
