# Generated by Django 5.0.14 on 2026-04-19 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('subjects', models.CharField(help_text='Comma-separated, e.g. Math, Physics', max_length=500)),
                ('classes_label', models.CharField(blank=True, max_length=200)),
                ('teaches_from', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('teaches_to', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('fee_label', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('rating_display', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_featured_home', models.BooleanField(default=False, help_text='Prioritize on the public home page (pilot city).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometutor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured_home', '-rating_display', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TutorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to='hometutor/docs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hometutor.tutorprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['city', 'verification_status'], name='hometutor_t_city_f9ed0a_idx'),
        ),
    ]
