# Generated by Django 5.0.14 on 2026-04-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_engagements(apps, schema_editor):
    DemoRequest = apps.get_model('hometutor', 'DemoRequest')
    TutorEngagement = apps.get_model('hometutor', 'TutorEngagement')
    for d in DemoRequest.objects.filter(status='ACCEPTED'):
        TutorEngagement.objects.get_or_create(
            demo_request=d,
            defaults={
                'tutor_profile_id': d.tutor_id,
                'student_id': d.requester_id,
                'status': 'PENDING_MUTUAL',
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hometutor', '0002_alter_tutorprofile_user_demorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='demo_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when ~24h reminder email was sent (idempotent).', null=True),
        ),
        migrations.CreateModel(
            name='TutorEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_MUTUAL', 'Awaiting both confirmations'), ('ACTIVE', 'Confirmed — ready to meet'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_MUTUAL', max_length=20)),
                ('parent_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tutor_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('mutual_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demo_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='hometutor.demorequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometutor_engagements', to=settings.AUTH_USER_MODEL)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='hometutor.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_engagements, noop),
    ]
