# Generated by Django 5.0.14 on 2026-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometutor', '0005_pincodegeo_tutorprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages, e.g. English, Hindi, Gujarati', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_mode',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], db_index=True, default='OFFLINE', max_length=20),
        ),
    ]
