# Generated by Django 5.0.14 on 2026-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometutor', '0006_tutorprofile_languages_tutorprofile_teaching_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hometutor/profile/%Y/%m/'),
        ),
    ]
