# Generated by Django 5.1.6 on 2026-07-11 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometutor', '0007_tutorprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='e.g. Sunita M.', max_length=80)),
                ('author_label', models.CharField(blank=True, help_text='e.g. Parent · Class 10 CBSE', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='hometutor.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
