# Generated by Django 5.0.14 on 2026-04-30 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyClassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(db_index=True)),
                ('topic', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('attendance', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_class_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentdailyclasslog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='uniq_daily_class_log_per_user_date'),
        ),
    ]
