# Generated by Django 5.0.14 on 2026-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_daily_class_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdailyclasslog',
            name='attendance',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], db_index=True, default='ABSENT', max_length=10),
        ),
    ]
