# Generated by Django 5.0.14 on 2026-07-20 07:06

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmssubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lms/submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.validators.validate_upload_size_mb(15)]),
        ),
        migrations.AlterField(
            model_name='lmssubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lms/submissions/%Y/%m/', validators=[core.validators.validate_upload_size_mb(10)]),
        ),
    ]
