# Generated by Django 5.1.6 on 2026-07-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsSubmissionUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('DRIVE', 'Google Drive'), ('WEBSITE', 'Website')], default='DRIVE', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='lms.lmssubmission')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
