# Generated by Django 5.1.6 on 2026-07-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_submission_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LMS topic',
                'verbose_name_plural': 'LMS topics',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='lmsassignment',
            options={'ordering': ['topic__title', '-created_at']},
        ),
        migrations.AddField(
            model_name='lmsassignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lms.lmstopic'),
        ),
    ]
