# Generated by Django 5.1.6 on 2026-07-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_revision_bites'),
        ('lms', '0005_general_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='concept_video',
            field=models.ForeignKey(blank=True, help_text='Optional lecture recording from /learning/ linked to this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='learning.conceptvideo'),
        ),
    ]
