# Generated by Django 5.1.6 on 2026-07-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_assignment_concept_video'),
        ('tutor_study', '0003_alter_studymaterial_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='study_topic',
            field=models.ForeignKey(blank=True, help_text='Optional Study hub topic from /admin/study/ linked to this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='tutor_study.studytopic'),
        ),
    ]
