# Generated by Django 5.0.14 on 2026-07-31 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_referrallinkclick'),
        ('lms', '0008_faculty_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscourse',
            name='catalog_course',
            field=models.ForeignKey(blank=True, help_text='Paid catalog course (/courses/) this batch delivers. Buyers auto-enroll into the default batch for this catalog course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='core.course'),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='is_default_for_catalog',
            field=models.BooleanField(default=False, help_text='If multiple batches deliver the same catalog course, new buyers auto-enroll into the one marked default.'),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Faculty/tutor who owns this course. Empty = platform-wide course (superuser managed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
