# Generated by Django 5.0.14 on 2026-07-31 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_userattempt_passed_and_more'),
        ('lms', '0009_lmscourse_catalog_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Optional graded test from /assessment/ linked to this assignment — course roster results roll up on the assignment page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_assignments', to='assessment.skill'),
        ),
    ]
