# Generated by Django 5.0.14 on 2026-07-31 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_lmsassignment_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmstopic',
            name='course',
            field=models.ForeignKey(blank=True, help_text="Optional: scope this topic to one course so it appears in that course's LMS sidebar right away, even before any assignment exists under it yet. Empty = platform-wide topic (only appears once an assignment under it exists).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='lms.lmscourse'),
        ),
    ]
