# Generated by Django 5.0.14 on 2026-07-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_lmstopic_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsassignment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Empty = platform-wide (superuser only). Otherwise scoped to this faculty course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms.lmscourse'),
        ),
        migrations.AlterField(
            model_name='lmstopic',
            name='course',
            field=models.ForeignKey(blank=True, help_text="Optional: scope this topic to one course so it appears in that course's LMS sidebar right away, even before any assignment exists under it yet. Empty = platform-wide topic (only appears once an assignment under it exists).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lms.lmscourse'),
        ),
    ]
