# Generated by Django 5.0.14 on 2026-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_lmsattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='is_free_preview',
            field=models.BooleanField(db_index=True, default=False, help_text="Show this assignment's concept_video as the public free preview on the linked catalog course."),
        ),
    ]
