# Generated by Django 5.0.14 on 2026-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_lmsassignment_is_free_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequence within its course — controls the order students unlock assignments in (lower first). Ties break by creation order.'),
        ),
    ]
