# Generated by Django 5.0.14 on 2026-08-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_userattempt_passed_and_more'),
        ('lms', '0015_lmsassignment_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscourse',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Class/track this course is for (e.g. Class 10th, Digital Skills Mastery). Empty = general/all levels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='assessment.skillpath'),
        ),
        migrations.AddField(
            model_name='lmstopic',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Class/track this topic is for (e.g. Class 10th, Digital Skills Mastery). Matters most for platform-wide topics (no course above): only students on this level see them — empty = general/visible to everyone, same as before.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_topics', to='assessment.skillpath'),
        ),
    ]
