# Generated by Django 5.0.14 on 2026-05-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=130)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutor_study.studytopic')),
                ('tutor', models.ForeignKey(blank=True, help_text='Empty = RankJee catalog chapter (any tutor can attach). Set for tutor-only chapters.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='studyassignment',
            name='study_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tutor_study.studytopic'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='study_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='tutor_study.studytopic'),
        ),
        migrations.AddConstraint(
            model_name='studytopic',
            constraint=models.UniqueConstraint(fields=('tutor', 'parent', 'slug'), name='study_topic_slug_unique_scope'),
        ),
    ]
