# Generated by Django 5.0.14 on 2026-07-20 07:06

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_study', '0002_study_topic_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF or image.', null=True, upload_to='study/materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), core.validators.validate_upload_size_mb(10)]),
        ),
    ]
