# Generated by Django 5.0.14 on 2026-03-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('concept_tag', models.CharField(max_length=50)),
                ('video_url', models.URLField(help_text='URL to video content')),
                ('duration_seconds', models.IntegerField(default=60)),
            ],
        ),
    ]
