# Generated by Django 5.0.14 on 2026-03-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_skillpath_skill_path'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptvideo',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Link this video to a specific skill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='assessment.skill'),
        ),
        migrations.AlterField(
            model_name='conceptvideo',
            name='video_url',
            field=models.URLField(help_text='Paste any YouTube link (watch, youtu.be, or shorts)'),
        ),
    ]
