# Generated by Django 5.0.1 on 2026-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_conceptvideo_skill_alter_conceptvideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a custom thumbnail or leave blank for auto YouTube thumbnail', null=True, upload_to='thumbnails/'),
        ),
    ]
