# Generated by Django 5.0.14 on 2026-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_conceptvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptvideo',
            name='text_summary',
            field=models.TextField(blank=True, help_text='Optional text revision bite for low-bandwidth users'),
        ),
    ]
