# Generated by Django 5.0.14 on 2026-05-11 04:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerBuyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RAM', 'RAM'), ('CPU', 'CPU'), ('SSD', 'SSD'), ('LOCATION', 'Location'), ('TERM', 'Billing term')], db_index=True, max_length=20)),
                ('key', models.SlugField(help_text='Stable value sent from the form, e.g. ram_8gb.', max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('monthly_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='For RAM/CPU/SSD/LOCATION: added to monthly subtotal. Use 0 for term rows.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('billing_months', models.PositiveSmallIntegerField(blank=True, help_text='TERM only: 12, 24, or 36 — multiplies monthly subtotal.', null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='TERM only: applied once to (monthly_subtotal × billing_months).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StudentServerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('ram_key', models.CharField(max_length=64)),
                ('cpu_key', models.CharField(max_length=64)),
                ('ssd_key', models.CharField(max_length=64)),
                ('location_key', models.CharField(max_length=64)),
                ('term_key', models.CharField(max_length=64)),
                ('monthly_subtotal_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_months', models.PositiveSmallIntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='serverbuyoption',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='serverbuyoption_category_key_uniq'),
        ),
        migrations.AddField(
            model_name='studentserverorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_buy_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
