# Generated by Django 5.0.14

from decimal import Decimal

from django.db import migrations


def seed_options(apps, schema_editor):
    ServerBuyOption = apps.get_model("server_buy", "ServerBuyOption")
    if ServerBuyOption.objects.exists():
        return

    def row(
        category,
        key,
        label,
        monthly_inr,
        billing_months=None,
        discount_percent=Decimal("0"),
        sort_order=0,
    ):
        ServerBuyOption.objects.create(
            category=category,
            key=key,
            label=label,
            monthly_inr=monthly_inr,
            billing_months=billing_months,
            discount_percent=discount_percent,
            sort_order=sort_order,
            is_active=True,
        )

    row("RAM", "ram_4gb", "4 GB RAM", Decimal("1500"), sort_order=10)
    row("RAM", "ram_8gb", "8 GB RAM", Decimal("2800"), sort_order=20)
    row("RAM", "ram_16gb", "16 GB RAM", Decimal("5200"), sort_order=30)

    row("CPU", "cpu_2", "2 vCPU", Decimal("900"), sort_order=10)
    row("CPU", "cpu_4", "4 vCPU", Decimal("1800"), sort_order=20)
    row("CPU", "cpu_8", "8 vCPU", Decimal("3600"), sort_order=30)

    row("SSD", "ssd_128", "128 GB SSD", Decimal("400"), sort_order=10)
    row("SSD", "ssd_256", "256 GB SSD", Decimal("700"), sort_order=20)
    row("SSD", "ssd_512", "512 GB SSD", Decimal("1200"), sort_order=30)

    row("LOCATION", "loc_in", "India region", Decimal("0"), sort_order=10)
    row("LOCATION", "loc_us", "USA region", Decimal("2500"), sort_order=20)

    row("TERM", "term_1y", "1 year (12 months)", Decimal("0"), 12, Decimal("0"), 10)
    row("TERM", "term_2y", "2 years (24 months) — 5% off", Decimal("0"), 24, Decimal("5"), 20)
    row("TERM", "term_3y", "3 years (36 months) — 10% off", Decimal("0"), 36, Decimal("10"), 30)


def unseed_options(apps, schema_editor):
    ServerBuyOption = apps.get_model("server_buy", "ServerBuyOption")
    ServerBuyOption.objects.filter(
        key__in=[
            "ram_4gb",
            "ram_8gb",
            "ram_16gb",
            "cpu_2",
            "cpu_4",
            "cpu_8",
            "ssd_128",
            "ssd_256",
            "ssd_512",
            "loc_in",
            "loc_us",
            "term_1y",
            "term_2y",
            "term_3y",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("server_buy", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_options, unseed_options),
    ]
