# Generated by Django 5.0.14 on 2026-05-11 05:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_buy', '0002_seed_default_server_buy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name shown in the list, e.g. Pro — India — 2 years.', max_length=120)),
                ('ram_spec', models.CharField(help_text='e.g. 8 GB', max_length=80)),
                ('cpu_spec', models.CharField(help_text='e.g. 4 vCPU', max_length=80)),
                ('ssd_spec', models.CharField(help_text='e.g. 256 GB SSD', max_length=80)),
                ('location', models.CharField(choices=[('INDIA', 'India'), ('USA', 'USA')], db_index=True, max_length=20)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(12, '1 year'), (24, '2 years'), (36, '3 years')], default=12, help_text='Billing period for this fixed price.')),
                ('price_inr', models.DecimalField(decimal_places=2, help_text='Total amount the student pays (one Razorpay charge).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal only — not shown on the buy page.')),
            ],
            options={
                'verbose_name': 'Server package',
                'verbose_name_plural': 'Server packages',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.DeleteModel(
            name='ServerBuyOption',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='billing_months',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='cpu_key',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='location_key',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='monthly_subtotal_inr',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='ram_key',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='ssd_key',
        ),
        migrations.RemoveField(
            model_name='studentserverorder',
            name='term_key',
        ),
        migrations.AddField(
            model_name='studentserverorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='server_buy.serverpackage'),
        ),
    ]
