# Generated by Django 5.0.14 on 2026-05-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_buy', '0004_seed_server_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerBuyMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('success_message', models.TextField(default='Your server payment was recorded successfully. Our team will contact you shortly for provisioning.', help_text='Shown to students on dashboard after server buy payment success.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server buy success message',
                'verbose_name_plural': 'Server buy success messages',
            },
        ),
    ]
