# Generated by Django 5.0.14 on 2026-05-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_buy', '0005_add_success_message_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_message', models.TextField(blank=True, help_text='Student-facing status note for this order. If blank, default processing message is shown.')),
                ('server_ip', models.CharField(blank=True, max_length=120)),
                ('panel_url', models.URLField(blank=True)),
                ('login_username', models.CharField(blank=True, max_length=120)),
                ('login_password', models.CharField(blank=True, max_length=120)),
                ('nameservers', models.TextField(blank=True, help_text='Optional: one per line or comma-separated.')),
                ('extra_details', models.TextField(blank=True, help_text='Any additional setup notes for the student.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='server_buy.studentserverorder')),
            ],
            options={
                'verbose_name': 'Server order detail',
                'verbose_name_plural': 'Server order details',
                'ordering': ('-updated_at',),
            },
        ),
    ]
